services:
  hall-ban-enforcer:
    image: ghcr.io/hackletloose/hall-banenforce:latest
    container_name: hall-ban-enforcer
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        restart: true
        condition: service_healthy
  db:
    container_name: ban-enforcer-db
    image: mariadb:lts
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_Root_Password}
      MYSQL_DATABASE: ${DB_Database}
      MYSQL_USER: ${DB_User}
      MYSQL_PASSWORD: ${DB_Password}
    ports:
      - 3306
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3